In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df_areas = pd.read_csv("Datasets/dubai_areas.csv")
df = pd.read_csv("Datasets/dubai_cold_coffee_spots_clean.csv")

In [5]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [6]:
df_areas

            area_name emoji     lat     lng
0      Downtown Dubai    🏙️  25.200  55.300
1      Jumeirah Beach     🌊  25.205  55.260
2        Business Bay     🏢  25.185  55.310
3           City Walk    🛍️  25.210  55.270
4             Al Safa     🕌  25.175  55.255
5   Sheikh Zayed Road     🌆  25.220  55.290
6                DIFC     🏨  25.215  55.285
7         Zabeel Park     🌳  25.230  55.320
8             Al Wasl     🏫  25.190  55.340
9           Oud Metha     🏪  25.240  55.315
10        Al Jafiliya     🚇  25.245  55.295
11        Al Mankhool    🏘️  25.165  55.305
12            Al Bada     🌴  25.155  55.330
13              Satwa     🏬  25.175  55.275

In [7]:
df_areas['Label']= df_areas['emoji'] +" " + df_areas['area_name']

In [8]:
df_areas

            area_name emoji     lat     lng                Label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [9]:
df_areas.to_csv("dubai_areas_label.csv")

In [10]:
aa=list(df_areas['Label'])

In [11]:
aa

['🏙️ Downtown Dubai',
 '🌊 Jumeirah Beach',
 '🏢 Business Bay',
 '🛍️ City Walk',
 '🕌 Al Safa',
 '🌆 Sheikh Zayed Road',
 '🏨 DIFC',
 '🌳 Zabeel Park',
 '🏫 Al Wasl',
 '🏪 Oud Metha',
 '🚇 Al Jafiliya',
 '🏘️ Al Mankhool',
 '🌴 Al Bada',
 '🏬 Satwa']

In [12]:
df["type"].unique()

array(['cart', 'truck', 'cafe'], dtype=object)

In [13]:
df_areas[df_areas['Label'] == "🌴 Al Bada"]

   area_name emoji     lat    lng      Label
12   Al Bada     🌴  25.155  55.33  🌴 Al Bada

In [14]:
ss = df_areas[df_areas['Label'] == "🌴 Al Bada"]["lat" , "lng"]
user_location = tuple(ss.iloc[0])

KeyError: ('lat', 'lng')

*Small Tasks For you Guys..:*
1. create a function that take a rating as an argument and return (⭐)
      for example if rating is *4.5*  then you have to return "⭐⭐⭐⭐ (4.5)"

*def rating_star(rating):*
     *pass*

2. create a function that return different icon according to spot type
     for example we have 
     icons = ["🏠","🛒","🚚","☕"]

     now create a function *get_spot_type_icon*
     this function will take *spot_type* as an argument and return icon
     if type is cafe return  🏠
     type is cart then return 🛒
    and for truck return 🚚
    and in else return ☕

*def get_spot_type_icon(spot_type):*
      *pass*


Functions you have to create in Practice file.

In [15]:
def rating_star(rating):

SyntaxError: incomplete input (2448091105.py, line 1)

In [16]:
def get_spot_type_icon(spot_type):
      sport_icon = [ ["🏠","🛒","🚚","☕"]]
    #   print("ENter Your chocie:")
      if spot_type == "cafe":
          print( "🏠" )
      elif spot_type == "cart":
          print( "🛒")
      elif spot_type == "truck":
          print( "🚚"  )
      else: 
          print( "☕")

In [17]:
get_spot_type_icon("truck")

🚚

In [18]:
def rating_star(rating):
    integer = int(rating)
    if rating == 0 :
        print(0)
    elif integer== 1:
        print("⭐" +  " " + str(rating))
    elif integer== 2:
        print("⭐⭐" + " " + str(rating))
    elif integer== 3:
        print("⭐⭐⭐" + " " + str(rating))
    elif integer== 4:
        print("⭐⭐⭐⭐"+ " " + str(rating))
    elif rating == 5:
        print("⭐⭐⭐⭐⭐"+" " + str(rating))
    else:
        print("Please Enter Rating Between 1 and 5")

rating_star(2.5)

⭐⭐ 2.5

In [19]:
def rating_star(rating):
    intg = int(rating)
    if rating<0 or rating>5:
        print("Please Enter Rating Between 1 and 5")
    else:
        print("⭐" * intg , "("+ str(rating) + ")")

In [20]:
rating_star(4.5)

⭐⭐⭐⭐ (4.5)

In [21]:
rating_star(6)

Please Enter Rating Between 1 and 5

In [22]:
rating_star(5)

⭐⭐⭐⭐⭐ (5)

In [23]:
rating_star(1)

⭐ (1)

In [24]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [25]:
df_areas

            area_name emoji     lat     lng                Label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [26]:
spot_type = "cafe"
a = df[df["type"] == spot_type]
# print(df[a])/
a

,name,lat,lng,type,rating,opening_time,closing_time
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00

In [27]:
import geopy

In [28]:
%pip install geopy

Requirement already satisfied: geopy in c:\users\hp\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\hp\anaconda3\lib\site-packages (from geopy) (2.1)
Note: you may need to restart the kernel to use updated packages.

In [29]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [30]:
df_areas

            area_name emoji     lat     lng                Label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [31]:
from geopy.distance import geodesic

user_location=(	25.245	,55.295	)
spot_loc =  (25.207773,	55.290559)
geodesic(user_location , spot_loc).km

4.148076617255297


def calc_dis(row):
    lat = row["lat"]
    lng = row['lng']
    spot_loc = (lat,lng)
    dis= geodesic(user_location, spot_loc).km
    return round(dis,2)

df["distance_km"] = df.apply(calc_dis , axis=1)

In [32]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [33]:
from datetime import datetime
row=df
def is_open(row):
    current_time = datetime.now().strftime("%H:%M")
    open_time = row["opening_time"]
    closing_time = row["closing_time"]
    if current_time <= open_time and current_time<=closing_time:
        return ("open")
        
    else :
        return("closed")

In [34]:
df["Current time status"]=df.apply(is_open,axis=1)

In [35]:
df

,name,lat,lng,type,rating,opening_time,closing_time,Current time status
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,closed
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,closed
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,closed
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,closed
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,closed
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,closed
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,closed
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,closed
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,closed
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,closed
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,closed
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,closed
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,closed
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,closed
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,closed
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,closed
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,closed
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,closed
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,closed
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,closed
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,closed
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,closed
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,closed
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,closed
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,closed
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,closed
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,closed
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,closed
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,closed
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,closed
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,closed
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,closed
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,closed
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,closed
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,closed
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,closed
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,closed
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,closed
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,closed
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,closed
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,closed
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,closed
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,closed
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,closed
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,closed
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,closed
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,closed
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,closed
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,closed
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,closed

In [36]:
df.value_counts()

name               lat        lng        type   rating  opening_time  closing_time  Current time status
Arctic Brew        25.228260  55.281833  cart   4.8     09:00         22:00         closed                 1
Route 66 Coffee    25.216620  55.342005  cart   4.4     06:00         20:00         closed                 1
Iced Rush          25.172374  55.271237  truck  4.9     06:00         21:00         closed                 1
Java Oasis         25.159588  55.305825  cart   4.5     10:00         23:00         closed                 1
Latte Land         25.154616  55.309822  cafe   4.1     07:00         22:00         closed                 1
Latte on the Go    25.248106  55.304331  cart   3.5     10:00         20:00         closed                 1
Mocha Motion       25.159676  55.337032  truck  4.2     08:00         23:00         closed                 1
Mug Life           25.220186  55.289355  truck  3.5     07:00         21:00         closed                 1
Nomad Brew         25.239391  55.306152  truck  4.9     09:00         21:00         closed                 1
Perk Up Cafe       25.246448  55.272767  cart   4.3     06:00         22:00         closed                 1
Pulse Cafe         25.182038  55.336626  cart   4.4     09:00         20:00         closed                 1
Quick Drip         25.243381  55.312097  cart   3.6     07:00         22:00         closed                 1
Shake Shack Cafe   25.239039  55.307756  cart   3.7     06:00         23:00         closed                 1
Bean Bazaar        25.198350  55.305205  truck  4.9     08:00         23:00         closed                 1
Shot Stop          25.235518  55.250343  cafe   5.0     08:00         22:00         closed                 1
Sip Stop           25.200194  55.297612  cart   4.6     08:00         22:00         closed                 1
Sippin’ Point      25.244079  55.331386  cart   4.4     08:00         20:00         closed                 1
Snowy Shot         25.230627  55.265882  truck  4.8     06:00         21:00         closed                 1
Steamy vs Icy      25.213372  55.344224  cafe   3.8     08:00         23:00         closed                 1
The Bean Scene     25.154320  55.340818  cafe   4.9     10:00         20:00         closed                 1
The Chill Spot     25.209224  55.304276  cafe   4.8     06:00         23:00         closed                 1
The Daily Brew     25.233261  55.330552  cart   4.0     06:00         21:00         closed                 1
The Ice Press      25.191494  55.314447  cafe   4.9     09:00         20:00         closed                 1
The Roasted Route  25.180392  55.254501  cafe   4.3     08:00         23:00         closed                 1
Iced Daily         25.213998  55.275438  cart   4.1     08:00         23:00         closed                 1
Iced & Easy        25.170497  55.311298  cafe   3.6     09:00         23:00         closed                 1
Grind House        25.203164  55.304382  cart   4.6     09:00         21:00         closed                 1
Frozen Grind       25.191297  55.335197  cart   4.1     06:00         23:00         closed                 1
Bean There         25.179933  55.326601  cafe   4.2     08:00         20:00         closed                 1
Brewed Awakening   25.207773  55.290559  cart   4.3     09:00         23:00         closed                 1
Brewie Louie       25.245210  55.253333  cafe   4.0     09:00         23:00         closed                 1
Brrrista           25.173272  55.252322  cafe   4.0     06:00         23:00         closed                 1
Buzz Station       25.201734  55.318113  cart   4.4     07:00         22:00         closed                 1
Cafe Mirage        25.166434  55.319951  cart   3.6     09:00         22:00         closed                 1
Caffeinated Camel  25.191213  55.269632  cart   4.7     09:00         20:00         closed                 1
Caffeine Cartel    25.217613  55.346531  cart   3.7     10:00         23:00         closed                 1
Café Breeze        25.150536  55.338752  cafe   4.5     07:00         22:00         closed                 1
Carafe Cart        25.199326  55.346555  truck  4.5     06:00         21:00         closed                 1
Chai Chiller       25.218065  55.269152  cafe   4.4     06:00         23:00         closed                 1
Chill & Spill      25.248509  55.301298  truck  4.7     08:00         20:00         closed                 1
Cold Culture       25.248168  55.327985  cafe   4.7     09:00         17:00         closed                 1
Cool Beans         25.192334  55.263833  cafe   4.8     09:00         21:00         closed                 1
Cooler Beans       25.212366  55.269280  cart   5.0     06:00         21:00         closed                 1
Desert Drip        25.161236  55.259174  cafe   3.8     06:00         23:00         closed                 1
Espresso Express   25.178230  55.256539  cart   4.9     09:00         20:00         closed                 1
Flat White Truck   25.179104  55.348576  cart   3.9     09:00         23:00         closed                 1
Frost & Found      25.190576  55.336748  truck  4.6     10:00         17:00         closed                 1
Frosty Mug         25.152942  55.295840  cafe   4.9     06:00         21:00         closed                 1
Frozen Feels       25.173230  55.280982  truck  4.7     08:00         23:00         closed                 1
Velvet Roast       25.186886  55.348506  cafe   3.7     08:00         17:00         closed                 1
Name: count, dtype: int64

In [37]:
rows = df.iloc[0:2]
for idx,row in rows.iterrows():
    print(row["name"] , row["type"] )

Brewed Awakening cart
Chill & Spill truck

In [38]:
for i in range(0,len(df) , 2):
    two_rows = df.iloc[i,i+2]
    for idx,row in rows.iterrows():
        print(row['name'] , row['type'] )

Brewed Awakening cart
Chill & Spill truck
Brewed Awakening cart
Chill & Spill truck
Brewed Awakening cart
Chill & Spill truck

IndexError: index 8 is out of bounds for axis 0 with size 8

In [ ]:
def get_spot_type_icon(spot_type):
      spot_icon = ["🏠","🛒","🚚","☕"]
    #   print("ENter Your chocie:")
      if spot_type == "cafe":
          print( spot_icon [0])
      elif spot_type == "cart":
          print( spot_icon[1])
      elif spot_type == "truck":
          print( spot_icon[2]  )
      else: 
          print( spot_icon[2])

In [39]:
get_spot_type_icon("cafe")

🏠

In [40]:
df['type'].unique()

array(['cart', 'truck', 'cafe'], dtype=object)

In [41]:
df['type'].value_counts()

type
cart     22
cafe     18
truck    10
Name: count, dtype: int64

In [42]:
df

,name,lat,lng,type,rating,opening_time,closing_time,Current time status
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,closed
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,closed
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,closed
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,closed
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,closed
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,closed
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,closed
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,closed
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,closed
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,closed
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,closed
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,closed
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,closed
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,closed
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,closed
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,closed
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,closed
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,closed
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,closed
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,closed
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,closed
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,closed
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,closed
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,closed
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,closed
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,closed
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,closed
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,closed
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,closed
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,closed
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,closed
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,closed
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,closed
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,closed
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,closed
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,closed
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,closed
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,closed
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,closed
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,closed
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,closed
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,closed
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,closed
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,closed
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,closed
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,closed
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,closed
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,closed
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,closed
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,closed

In [43]:
open_spots= len(df['is_open'] == "Open")

KeyError: 'is_open'

In [44]:
df2=df.copy()
# open_spots= len(df2[df2["is_open"] == "Open"])
open_spots = df2[df2["is_open"] == "Open"]

KeyError: 'is_open'

In [45]:
df2=df.copy()

In [46]:
average_rating = df2.groupby(["type" , "rating"].mean())

AttributeError: 'list' object has no attribute 'mean'

In [47]:
average_rating = df2.groupby("type")["rating"].mean()

In [48]:
average_rating

type
cafe     4.355556
cart     4.250000
truck    4.570000
Name: rating, dtype: float64

In [49]:
df['type'].value_counts().mean()

16.666666666666668

In [52]:
da = df.copy()
da = da.sort_values(by="rating" , ascending= False).reset_index()

In [53]:
da

,index,name,lat,lng,type,rating,opening_time,closing_time,Current time status
0,27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,closed
1,41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,closed
2,28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,closed
3,2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,closed
4,4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,closed
5,31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,closed
6,6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,closed
7,33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,closed
8,37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,closed
9,16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,closed
10,34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,closed
11,38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,closed
12,5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,closed
13,22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,closed
14,48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,closed
15,1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,closed
16,44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,closed
17,25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,closed
18,15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,closed
19,13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,closed
20,24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,closed
21,39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,closed
22,47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,closed
23,21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,closed
24,40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,closed
25,30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,closed
26,29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,closed
27,32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,closed
28,46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,closed
29,0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,closed
30,9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,closed
31,7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,closed
32,12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,closed
33,49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,closed
34,43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,closed
35,8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,closed
36,20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,closed
37,45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,closed
38,10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,closed
39,19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,closed
40,23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,closed
41,42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,closed
42,3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,closed
43,26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,closed
44,35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,closed
45,14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,closed
46,17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,closed
47,36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,closed
48,18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,closed
49,11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,closed